sudo: required
language: generic 
service:
  - docker

before_install:
  - docker build -t cppragada/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cppragada/docker-react npm run test -- --coverage